import {
  Dashboard,
  People,
  MenuBook,
  Groups,
  Feedback,
  FormatListNumbered,
  Reviews,
  Book,
  LiveHelp,
  Language,
  Settings,
  OtherHouses,
  ManageAccounts,
  Diversity1,
  VerifiedUser,
  ShowChart,
  Handshake,
  EmojiEvents,
  VideoCameraFront,
  QuestionAnswer,
  AdminPanelSettings,
  Person,
  PersonPin,
  PermPhoneMsg,
  DisplaySettings,
  Devices,
  RadioButtonChecked,
  RoomPreferences,
  HomeWork,
  Home,
} from "@mui/icons-material";

export const menuItems = [
  { name: "Dashboard", icon: <Dashboard />, path: "/admin" },
  {
    name: "Staff Management",
    icon: <Diversity1 />,
    path: "/admin/staff-management",
    children: [
      {
        name: "Staff",
        icon: <Groups />,
        path: "/admin/staff-management/staff",
        requiredPermission: "view_all_staffs",
      },
      {
        name: "Roles",
        icon: <ManageAccounts />,
        path: "/admin/staff-management/role",
        requiredPermission: "view_staff_roles",
      },
      {
        name: "Permissions",
        icon: <VerifiedUser />,
        path: "/admin/staff-management/permission",
        requiredPermission: "view_all_permissions",
      },
    ],
  },
  {
    name: "Facilities Management",
    icon: <OtherHouses />,
    path: "/admin/facilities-management",
    children: [
      {
        name: "Facilities",
        icon: <RoomPreferences />,
        path: "/admin/facilities-management/facilities-listing",
        requiredPermission: "view_all_facilities",
      },
      {
        name: "Amenities",
        icon: <HomeWork />,
        path: "/admin/facilities-management/amenities-listing",
        requiredPermission: "view_all_amenities",
      },
      {
        name: "Space Types",
        icon: <Home />,
        path: "/admin/facilities-management/space-types-listing",
        requiredPermission: "view_all_space_types",
      },
    ],
  },
  // { name: "Admin", icon: <People />, path: "/admin/admin-listing" },
  {
    name: "Course Management",
    icon: <MenuBook />,
    children: [
      {
        name: "Course",
        icon: <MenuBook />,
        path: "/admin/course-listing",
      },
      {
        name: "Category",
        icon: <FormatListNumbered />,
        path: "/admin/category-listing",
      },
    ],
  },
  {
    name: "Instructor",
    icon: <Groups />,
    path: "/admin/instructor-listing",
    requiredPermission: "view_all_instructors",
  },
  {
    name: "Student",
    icon: <Feedback />,
    path: "/admin/student-listing",
    requiredPermission: "view_all_students",
  },
  {
    name: "Language",
    icon: <Language />,
    path: "/admin/languages-listing",
    requiredPermission: "view_all_languages",
  },
  {
    name: "Meeting",
    icon: <VideoCameraFront />,
    path: "/admin/meetings-listing",
    requiredPermission: "view_all_meetings",
  },
  {
    name: "Contact Inquiries",
    icon: <PermPhoneMsg />,
    path: "/admin/contact-inquiries",
    requiredPermission: "view_all_inquiries",
  },
  {
    name: "Faqs",
    icon: <LiveHelp />,
    path: "/admin/faqs",
    children: [
      {
        name: "Faqs Listing",
        icon: <LiveHelp />,
        path: "/admin/faqs/faqs-listing",
        requiredPermission: "view_all_faqs",
      },
      {
        name: "Faqs Categories",
        icon: <FormatListNumbered />,
        path: "/admin/faqs/faqs-categories",
        requiredPermission: "view_all_faqs_categories",
      },
    ],
  },
  {
    name: "Blogs",
    icon: <Book />,
    path: "/admin/blogs",
    children: [
      {
        name: "Blogs Listing",
        icon: <Book />,
        path: "/admin/blogs/blogs-listing",
        requiredPermission: "view_all_posts",
      },
      {
        name: "Blogs Categories",
        icon: <FormatListNumbered />,
        path: "/admin/blogs/blogs-categories",
        requiredPermission: "view_all_posts_categories",
      },
    ],
  },
  {
    name: "Website Setup",
    icon: <DisplaySettings />,
    path: "/admin/website",
    children: [
      {
        name: "Appearance",
        icon: <RadioButtonChecked />,
        path: "/admin/website/appearance",
        requiredPermission: "add_edit_admin_auth",
      },
      {
        name: "Header",
        icon: <RadioButtonChecked />,
        path: "/admin/website/header",
        requiredPermission: "add_edit_student_auth",
      },
      {
        name: "Footer",
        icon: <RadioButtonChecked />,
        path: "/admin/website/footer",
        requiredPermission: "add_edit_student_auth",
      },
      {
        name: "Pages",
        icon: <RadioButtonChecked />,
        path: "/admin/website/pages",
        requiredPermission: "view_all_pages",
      },
    ],
  },

  {
    name: "Settings",
    icon: <Settings />,
    path: "/admin/settings",
    children: [
      {
        name: "Testimonial",
        icon: <Reviews />,
        path: "/admin/settings/testimonials-listing",
        requiredPermission: "view_all_testimonials",
      },
      {
        name: "Stats",
        icon: <ShowChart />,
        path: "/admin/settings/stats-listing",
        requiredPermission: "view_all_stats",
      },
      {
        name: "Our Partners",
        icon: <Handshake />,
        path: "/admin/settings/partners-listing",
        requiredPermission: "view_all_partners",
      },
      {
        name: "Achievements",
        icon: <EmojiEvents />,
        path: "/admin/settings/achievements-listing",
        requiredPermission: "view_all_achievements",
      },
      {
        name: "Student Questions",
        icon: <QuestionAnswer />,
        path: "/admin/settings/student-questions-listing",
        requiredPermission: "view_all_questions",
      },
    ],
  },
  {
    name: "Auth Settings",
    icon: <ManageAccounts />,
    path: "/admin/auth-settings",
    children: [
      {
        name: "Admin Auth",
        icon: <AdminPanelSettings />,
        path: "/admin/auth-settings/admin",
        requiredPermission: "add_edit_admin_auth",
      },
      {
        name: "Student Auth",
        icon: <Person />,
        path: "/admin/auth-settings/student",
        requiredPermission: "add_edit_student_auth",
      },
      {
        name: "Trainer Auth",
        icon: <PersonPin />,
        path: "/admin/auth-settings/trainer",
        requiredPermission: "add_edit_trainer_auth",
      },
    ],
  },
];
